name: compile Guide

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.ash'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- uses: actions/setup-node@v1
      #- run: npm init -y
      #- run: npm install @actions/core
      #- run: npm install @actions/github

      - id: compile
        name: Forward output
        #uses: ./.github/actions
        shell: python
        run: |
          import os
          # Get out of the '.github' folder
          while '.github' in os.getcwd(): os.chdir('..')
          
          # The script that compiles the target script. First argument is the target script. Second argument (optional) is the path to reach the "mafia folder".
          py Compile_ASH_script.compile('relay/relay_TourGuide.ash', 'Source/')
      #- run: echo "The time was ${{ steps.compile.outputs.compiled_output }}"
  #push_to_branch:
    #needs: build
    #runs-on: windows-lastest
