name: compile Guide

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.ash'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: compile
        run: ./.github/actions/action.yml
      - run: echo "The time was ${{ steps.compile.outputs.compiled_output }}"
  #push_to_branch:
    #needs: build
    #runs-on: windows-lastest
